document.writeln("    <link rel=\'stylesheet\' href=\'css/header.css\'></link>");
document.writeln("    <div id=\'header\'>");
document.writeln("        <img id=\'logo\' src=\'img/logo.JPG\' class=\'img-style\'>");
document.writeln("        <div id=\'min-logo\'>");
document.writeln("            <div class=\'float-left\'><img  src=\'img/logo111.jpg\'></div>");
document.writeln("            <div id=\'right-logo\' class=\'float-right\' style=\'margin-right: 63px;\'><img src=\'img/logo222.jpg\'></div>");
document.writeln("        </div>");
document.writeln("        <div class=\'clearfix\'></div>");
document.writeln("");
document.writeln("        <button id=\'toggler\' class=\'navbar-light navbar-toggler collapsed\' data-toggle=\'collapse\' data-target=\'#nav-toggle\'>");
document.writeln("            <span class=\'navbar-toggler-icon\'></span>");
document.writeln("        </button>");
document.writeln("        <nav class=\'navbar navbar-expand-lg navbar-light\' id=\'min-navbar\'>");
document.writeln("            <div class=\'collapse navbar-collapse\' id=\'nav-toggle\'>");
document.writeln("                <ul class=\'navbar-nav mx-auto\'>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>誉材银行招考</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>师资力量</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>招考公告</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>时政热点</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>精品课程</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>每日一练</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>网申指导</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>在线报名</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </nav>");
document.writeln("");
document.writeln("        <nav id=\'navbar\' class=\'navbar navbar-expand-lg navbar-light\'>");
document.writeln("            <div class=\'collapse navbar-collapse\'>");
document.writeln("                <ul class=\'navbar-nav mx-auto\'>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>誉材银行招考</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>师资力量</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>招考公告</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>时政热点</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>精品课程</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>每日一练</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>网申指导</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\'>在线报名</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </nav>");
document.writeln("    </div>");