package com.hyg.yucai.model;

import java.util.ArrayList;
import java.util.List;

public class TStarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public TStarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStaridIsNull() {
            addCriterion("starId is null");
            return (Criteria) this;
        }

        public Criteria andStaridIsNotNull() {
            addCriterion("starId is not null");
            return (Criteria) this;
        }

        public Criteria andStaridEqualTo(Integer value) {
            addCriterion("starId =", value, "starid");
            return (Criteria) this;
        }

        public Criteria andStaridNotEqualTo(Integer value) {
            addCriterion("starId <>", value, "starid");
            return (Criteria) this;
        }

        public Criteria andStaridGreaterThan(Integer value) {
            addCriterion("starId >", value, "starid");
            return (Criteria) this;
        }

        public Criteria andStaridGreaterThanOrEqualTo(Integer value) {
            addCriterion("starId >=", value, "starid");
            return (Criteria) this;
        }

        public Criteria andStaridLessThan(Integer value) {
            addCriterion("starId <", value, "starid");
            return (Criteria) this;
        }

        public Criteria andStaridLessThanOrEqualTo(Integer value) {
            addCriterion("starId <=", value, "starid");
            return (Criteria) this;
        }

        public Criteria andStaridIn(List<Integer> values) {
            addCriterion("starId in", values, "starid");
            return (Criteria) this;
        }

        public Criteria andStaridNotIn(List<Integer> values) {
            addCriterion("starId not in", values, "starid");
            return (Criteria) this;
        }

        public Criteria andStaridBetween(Integer value1, Integer value2) {
            addCriterion("starId between", value1, value2, "starid");
            return (Criteria) this;
        }

        public Criteria andStaridNotBetween(Integer value1, Integer value2) {
            addCriterion("starId not between", value1, value2, "starid");
            return (Criteria) this;
        }

        public Criteria andStarnameIsNull() {
            addCriterion("starName is null");
            return (Criteria) this;
        }

        public Criteria andStarnameIsNotNull() {
            addCriterion("starName is not null");
            return (Criteria) this;
        }

        public Criteria andStarnameEqualTo(String value) {
            addCriterion("starName =", value, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameNotEqualTo(String value) {
            addCriterion("starName <>", value, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameGreaterThan(String value) {
            addCriterion("starName >", value, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameGreaterThanOrEqualTo(String value) {
            addCriterion("starName >=", value, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameLessThan(String value) {
            addCriterion("starName <", value, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameLessThanOrEqualTo(String value) {
            addCriterion("starName <=", value, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameLike(String value) {
            addCriterion("starName like", value, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameNotLike(String value) {
            addCriterion("starName not like", value, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameIn(List<String> values) {
            addCriterion("starName in", values, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameNotIn(List<String> values) {
            addCriterion("starName not in", values, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameBetween(String value1, String value2) {
            addCriterion("starName between", value1, value2, "starname");
            return (Criteria) this;
        }

        public Criteria andStarnameNotBetween(String value1, String value2) {
            addCriterion("starName not between", value1, value2, "starname");
            return (Criteria) this;
        }

        public Criteria andStarimgIsNull() {
            addCriterion("starImg is null");
            return (Criteria) this;
        }

        public Criteria andStarimgIsNotNull() {
            addCriterion("starImg is not null");
            return (Criteria) this;
        }

        public Criteria andStarimgEqualTo(String value) {
            addCriterion("starImg =", value, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgNotEqualTo(String value) {
            addCriterion("starImg <>", value, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgGreaterThan(String value) {
            addCriterion("starImg >", value, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgGreaterThanOrEqualTo(String value) {
            addCriterion("starImg >=", value, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgLessThan(String value) {
            addCriterion("starImg <", value, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgLessThanOrEqualTo(String value) {
            addCriterion("starImg <=", value, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgLike(String value) {
            addCriterion("starImg like", value, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgNotLike(String value) {
            addCriterion("starImg not like", value, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgIn(List<String> values) {
            addCriterion("starImg in", values, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgNotIn(List<String> values) {
            addCriterion("starImg not in", values, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgBetween(String value1, String value2) {
            addCriterion("starImg between", value1, value2, "starimg");
            return (Criteria) this;
        }

        public Criteria andStarimgNotBetween(String value1, String value2) {
            addCriterion("starImg not between", value1, value2, "starimg");
            return (Criteria) this;
        }

        public Criteria andStardescriptionIsNull() {
            addCriterion("starDescription is null");
            return (Criteria) this;
        }

        public Criteria andStardescriptionIsNotNull() {
            addCriterion("starDescription is not null");
            return (Criteria) this;
        }

        public Criteria andStardescriptionEqualTo(String value) {
            addCriterion("starDescription =", value, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionNotEqualTo(String value) {
            addCriterion("starDescription <>", value, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionGreaterThan(String value) {
            addCriterion("starDescription >", value, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("starDescription >=", value, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionLessThan(String value) {
            addCriterion("starDescription <", value, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionLessThanOrEqualTo(String value) {
            addCriterion("starDescription <=", value, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionLike(String value) {
            addCriterion("starDescription like", value, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionNotLike(String value) {
            addCriterion("starDescription not like", value, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionIn(List<String> values) {
            addCriterion("starDescription in", values, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionNotIn(List<String> values) {
            addCriterion("starDescription not in", values, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionBetween(String value1, String value2) {
            addCriterion("starDescription between", value1, value2, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStardescriptionNotBetween(String value1, String value2) {
            addCriterion("starDescription not between", value1, value2, "stardescription");
            return (Criteria) this;
        }

        public Criteria andStarbigimgIsNull() {
            addCriterion("starBigimg is null");
            return (Criteria) this;
        }

        public Criteria andStarbigimgIsNotNull() {
            addCriterion("starBigimg is not null");
            return (Criteria) this;
        }

        public Criteria andStarbigimgEqualTo(String value) {
            addCriterion("starBigimg =", value, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgNotEqualTo(String value) {
            addCriterion("starBigimg <>", value, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgGreaterThan(String value) {
            addCriterion("starBigimg >", value, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgGreaterThanOrEqualTo(String value) {
            addCriterion("starBigimg >=", value, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgLessThan(String value) {
            addCriterion("starBigimg <", value, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgLessThanOrEqualTo(String value) {
            addCriterion("starBigimg <=", value, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgLike(String value) {
            addCriterion("starBigimg like", value, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgNotLike(String value) {
            addCriterion("starBigimg not like", value, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgIn(List<String> values) {
            addCriterion("starBigimg in", values, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgNotIn(List<String> values) {
            addCriterion("starBigimg not in", values, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgBetween(String value1, String value2) {
            addCriterion("starBigimg between", value1, value2, "starbigimg");
            return (Criteria) this;
        }

        public Criteria andStarbigimgNotBetween(String value1, String value2) {
            addCriterion("starBigimg not between", value1, value2, "starbigimg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_star
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 04 15:20:16 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}