package com.hyg.yucai.model;

public class TStar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_star.starId
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    private Integer starid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_star.starName
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    private String starname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_star.starImg
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    private String starimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_star.starDescription
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    private String stardescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_star.starBigimg
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    private String starbigimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_star.starId
     *
     * @return the value of t_star.starId
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public Integer getStarid() {
        return starid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_star.starId
     *
     * @param starid the value for t_star.starId
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public void setStarid(Integer starid) {
        this.starid = starid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_star.starName
     *
     * @return the value of t_star.starName
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public String getStarname() {
        return starname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_star.starName
     *
     * @param starname the value for t_star.starName
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public void setStarname(String starname) {
        this.starname = starname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_star.starImg
     *
     * @return the value of t_star.starImg
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public String getStarimg() {
        return starimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_star.starImg
     *
     * @param starimg the value for t_star.starImg
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public void setStarimg(String starimg) {
        this.starimg = starimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_star.starDescription
     *
     * @return the value of t_star.starDescription
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public String getStardescription() {
        return stardescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_star.starDescription
     *
     * @param stardescription the value for t_star.starDescription
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public void setStardescription(String stardescription) {
        this.stardescription = stardescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_star.starBigimg
     *
     * @return the value of t_star.starBigimg
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public String getStarbigimg() {
        return starbigimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_star.starBigimg
     *
     * @param starbigimg the value for t_star.starBigimg
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    public void setStarbigimg(String starbigimg) {
        this.starbigimg = starbigimg;
    }
}