package com.hyg.yucai.mapper;

import com.hyg.yucai.model.TStar;
import com.hyg.yucai.model.TStarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TStarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    long countByExample(TStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    int deleteByExample(TStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    int deleteByPrimaryKey(Integer starid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    int insert(TStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    int insertSelective(TStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    List<TStar> selectByExample(TStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    TStar selectByPrimaryKey(Integer starid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") TStar record, @Param("example") TStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    int updateByExample(@Param("record") TStar record, @Param("example") TStarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    int updateByPrimaryKeySelective(TStar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_star
     *
     * @mbg.generated Tue Sep 04 15:20:16 CST 2018
     */
    int updateByPrimaryKey(TStar record);
}