package com.hyg.yucai.mapper;

import com.hyg.yucai.model.TVideo;
import com.hyg.yucai.model.TVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    long countByExample(TVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    int deleteByExample(TVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    int deleteByPrimaryKey(Integer videoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    int insert(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    int insertSelective(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    List<TVideo> selectByExample(TVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    TVideo selectByPrimaryKey(Integer videoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") TVideo record, @Param("example") TVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    int updateByExample(@Param("record") TVideo record, @Param("example") TVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    int updateByPrimaryKeySelective(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbg.generated Tue Sep 04 16:39:04 CST 2018
     */
    int updateByPrimaryKey(TVideo record);
}